- id: '1575922124106'
  alias: Close the blinds as dusk
  description: ''
  trigger:
  - event: sunset
    offset: +00:30:00
    platform: sun
  condition: []
  action:
  - alias: ''
    data:
      entity_id: all
    service: cover.close_cover
- id: '1575923914112'
  alias: ifttt_webhook
  trigger:
  - event_data:
      action: call_service
    event_type: ifttt_webhook_received
    platform: event
  action:
  - data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
    service_template: '{{ trigger.event.data.service }}'
- id: '1576537003318'
  alias: ifttt_webhook_params
  trigger:
  - platform: event
    event_data:
      action: call_service_with_params
    event_type: ifttt_webhook_received
  action:
  - service_template: '{{ trigger.event.data.service }}'
    data_template:
      brightness: '{{ trigger.event.data.brightness }}'
      effect: '{{ trigger.event.data.effect }}'
      entity_id: '{{ trigger.event.data.entity_id }}'
- id: '1580936086819'
  alias: ifttt kodi rpc
  description: ''
  trigger:
  - platform: event
    event_data:
      action: kodi_rpc_service
    event_type: ifttt_webhook_received
  condition: []
  action:
  - service_template: '{{ trigger.event.data.service }}'
    data_template:
      method: '{{ trigger.event.data.method }}'
- id: '1576675828079'
  alias: Presence - Nobody home
  description: ''
  trigger:
  - entity_id: group.all_persons
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      message: Nobody is home right now
    service: notify.telegram_td
- id: '1576676147603'
  alias: 'Lights on: Nobody home and lights on'
  description: ''
  trigger:
  - entity_id: group.all_persons
    for: 00:02:00
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: group.all_my_lights
    state: 'on'
  action:
  - service: telegram_bot.send_message
    data_template:
      inline_keyboard:
      - Turn off:/off
      target:
      - '{{ states(''input_text.telegram_td'') }}'
      - '{{ states(''input_text.telegram_ad'') }}'
      message: 💡 Nobody is home but lights have been left on
  - alias: ''
    data: {}
    entity_id: automation.lights_on_repeat_notification
    service: automation.turn_on
- id: '1576771228052'
  alias: 'Lights on: repeat notification'
  description: This automation is turned on by the "nobody home" automation and fires
    every 15 mins.
  trigger:
  - minutes: /15
    platform: time_pattern
  condition: []
  action:
  - service: telegram_bot.send_message
    data_template:
      inline_keyboard:
      - Turn off:/off
      target:
      - '{{ states(''input_text.telegram_td'') }}'
      - '{{ states(''input_text.telegram_ad'') }}'
      message: Nobody is home but lights have been left on . I'll remind you every
        15 minutes.
  initial_state: false
- id: '1576772552665'
  alias: 'Lights on: disable repeat notification'
  description: ''
  trigger:
  - entity_id: group.all_my_lights
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: switch.christmas_star
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: automation.lights_on_repeat_notification
      state: 'on'
    - condition: state
      entity_id: group.all_my_lights
      state: 'off'
  action:
  - data:
      entity_id: automation.lights_on_repeat_notification
    service: automation.turn_off
- id: '1576773012546'
  alias: Presence - Somebody arrived home
  description: ''
  trigger:
  - entity_id: group.all_persons
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data_template:
      message: "{%- for person in states.group.all_persons.attributes.entity_id -%}\n\
        \  {%- if is_state(person, 'home') -%} \n    {{ state_attr(person, 'friendly_name')\
        \ }} just arrived home\n  {%- endif -%}\n{%- endfor -%} \n"
    service: notify.telegram_td
- id: '1576773914306'
  alias: Telegram /off
  description: Respond to a manually typed Telegram message of "/off" (using telegram_command)
    or a "/off"  message from the inline_keyboard notification button (using telegram_callback)
  trigger:
  - event_data:
      command: /off
    event_type: telegram_callback
    platform: event
  - event_data:
      command: /off
    event_type: telegram_command
    platform: event
  condition: []
  action:
  - data:
      entity_id: all
    service: light.turn_off
  - data:
      entity_id: switch.sonoff_10001f5fa0
    service: switch.turn_off
  - data:
      entity_id: switch.christmas_star
    service: switch.turn_off
  - service: telegram_bot.send_message
    data_template:
      target:
      - '{{ states(''input_text.telegram_td'') }}'
      - '{{ states(''input_text.telegram_ad'') }}'
      message: All lights turned off.
- id: '1577980276286'
  alias: Presence - Left work (Tom)
  description: Send a telegram notification when Tom has been away from work for 2
    minutes
  trigger:
  - entity_id: person.tom
    for: 00:02:00
    from: BJSS
    platform: state
    to: not_home
  condition:
  - condition: template
    value_template: '{{ not is_state(''sensor.oneplus5t_wifi_connection'', ''BJSS-Staff'')
      }}'
  - after: '16:30'
    condition: time
  action:
  - data:
      message: Tom left work 2 minutes ago
    service: notify.telegram_td
- id: '1578494385278'
  alias: Presence - Left work (Anna)
  description: Send a Telegram notification when Anna been away from work for 2 minutes
  trigger:
  - entity_id: person.anna
    for: 00:02:00
    from: AD Work
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      message: Anna left work 2 minutes ago.
    service: notify.telegram_td
- id: '1578592845893'
  alias: 'Presence: Left Leeds (Tom)'
  description: Send a Telegram notification when Tom been away from work for 2 minutes
  trigger:
  - entity_id: person.tom
    for: 00:02:00
    from: Leeds Station
    platform: state
    to: not_home
  condition:
  - after: '16:30'
    condition: time
  action:
  - service: telegram_bot.send_message
    data_template:
      target:
      - '{{ states(''input_text.telegram_td'') }}'
      - '{{ states(''input_text.telegram_ad'') }}'
      message: Tom left Leeds Station 2 minutes ago
- id: '1580903225785'
  alias: 'Presence: Greeting'
  description: Play a greeting when Tom arrives home
  trigger:
  - entity_id: person.tom
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - delay: 00:00:30
  - data_template:
      message: Hello Tom, {{ states('sensor.compliment') }}
    entity_id: media_player.hallway_home
    service: tts.google_translate_say
- id: '1580921419430'
  alias: 'Trains: Update Next LDS-SHY train'
  description: Between the hours of 16:00 and 18:00 update the LDS-SHY train sensor
    every 15 minutes
  trigger:
  - hours: '16'
    minutes: /2
    platform: time_pattern
  - hours: '17'
    minutes: /15
    platform: time_pattern
  condition: []
  action:
  - entity_id: sensor.next_train_to_shy
    service: homeassistant.update_entity
- id: '1580923110072'
  alias: 'Trains: Update Next SHY-LDS train'
  description: Between the hours of 07:00 and 09:00 update the SHY-LDS train sensor
  trigger:
  - hours: '07'
    minutes: /2
    platform: time_pattern
  - hours: 08
    minutes: /15
    platform: time_pattern
  condition: []
  action:
  - entity_id: sensor.next_train_to_lds
    service: homeassistant.update_entity
- id: '1580937267396'
  alias: 'Kodi: Dim lights when playing'
  description: ''
  trigger:
  - entity_id: media_player.kodi
    platform: state
    to: playing
  condition:
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - data:
      brightness: 5
    entity_id: light.living_room_1, light.living_room_2
    service: light.turn_on
- id: '1580937548623'
  alias: 'Kodi: Brighten lights when stop playing'
  description: ''
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: paused
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: idle
  - entity_id: media_player.kodi
    from: paused
    platform: state
    to: idle
  condition: []
  action:
  - data:
      brightness: 200
    entity_id: light.living_room_1, light.living_room_2
    service: light.turn_on
- id: '1581026602537'
  alias: 'Dehumidifier: Turn on'
  description: ''
  trigger:
  - above: '80'
    entity_id: sensor.ensuite_humidity
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.dehumidifier
    service: switch.turn_on
- id: '1581026980222'
  alias: 'Dehumidifier: Turn off'
  description: ''
  trigger:
  - below: '70'
    entity_id: sensor.ensuite_humidity
    for: 00:05:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.dehumidifier
    state: 'on'
  action:
  - entity_id: switch.dehumidifier
    service: switch.turn_off
- id: '1581757504089'
  alias: Printer - Notify when complete
  description: Send a telegram and broadcast to Google Home when Printer is done
  trigger:
  - entity_id: binary_sensor.printer_printing
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: and
    conditions:
    - above: '95'
      condition: numeric_state
      entity_id: sensor.printer_job_percentage
  action:
  - data:
      message: The 3D Printer has finished
    service: notify.telegram_td
  - data:
      entity_id: media_player.living_room_display
      message: The printer has finished
    service: tts.google_translate_say
- id: '1581776307274'
  alias: 'Washer: Notify done (repeat)'
  description: ''
  trigger:
  - minutes: /15
    platform: time_pattern
  condition: []
  action:
  - data_template:
      entity_id: media_player.living_room_display
      message: The washing machine finished {{ relative_time(states.binary_sensor.washer.last_changed)
        }}ago, please hang out the washing
    service: tts.google_translate_say
  - data_template:
      inline_keyboard:
      - Washer Emptied:/washer_emptied
      message: 🧺 The washing machine finished {{ relative_time(states.binary_sensor.washer.last_changed)
        }} ago, please hang out the washing
      target:
      - '{{ states(''input_text.telegram_td'') }}'
      - '{{ states(''input_text.telegram_ad'') }}'
    service: telegram_bot.send_message
- id: '1581777155699'
  alias: 'Washer: Machine finished'
  description: ''
  trigger:
  - entity_id: binary_sensor.washer
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: automation.washer_notify_done
    service: automation.turn_on
  - entity_id: automation.washer_notify_done
    service: automation.trigger
- id: '1581777529393'
  alias: 'Washer: Handle *washer_emptied* telegram message'
  description: ''
  trigger:
  - event_data:
      command: /washer_emptied
    event_type: telegram_callback
    platform: event
  - event_data:
      command: /washer_emptied
    event_type: telegram_command
    platform: event
  condition: []
  action:
  - entity_id: automation.washer_notify_done
    service: automation.turn_off
  - data_template:
      message: 'Great! The forecast for today is: {{ state_attr(''weather.millview'',
        ''temperature'') }}°C, {{ states(''weather.millview'')}}. Wind speed is {{
        state_attr(''weather.millview'', ''wind_speed'') }}km/h.'
      target:
      - '{{ states(''input_text.telegram_td'') }}'
      - '{{ states(''input_text.telegram_ad'') }}'
    service: telegram_bot.send_message
- id: '1582057191428'
  alias: Printer - Telegram command
  description: Respond to */print* Telegram command with stats about 3D printer
  trigger:
  - event_data:
      command: /printer
    event_type: telegram_callback
    platform: event
  - event_data:
      command: /printer
    event_type: telegram_command
    platform: event
  condition: []
  action:
  - data_template:
      message: "Status: {{ states('sensor.printer_current_state') }}  \nElapsed: {%-\
        \ if states('sensor.printer_time_elapsed') |int > 3600 -%} {{ states('sensor.printer_time_elapsed')\
        \  | multiply(0.0002777778) | round(2)}}h {%- else %} {{ states('sensor.printer_time_elapsed')}}m\
        \ {% endif %}\nRemaining: {%- if states('sensor.printer_time_remaining') |int\
        \ > 3600 -%} {{ states('sensor.printer_time_remaining')  | multiply(0.0002777778)\
        \ | round(2)}}h {%- else %} {{ states('sensor.printer_time_remaining')}}m\
        \ {% endif %} \nProgress: {{ states('sensor.printer_job_percentage') }}%\n"
    service: notify.telegram_td
- id: '1582836882523'
  alias: Blanket - turn off TD after 10m
  description: Turn off Toms blanket 10m after it is turned on
  trigger:
  - entity_id: switch.blanket_tom
    for: 00:15:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.blanket_tom
    service: switch.turn_off
- id: '1583963701174'
  alias: Telegram - cam1
  description: ''
  trigger:
  - event_data:
      command: /cam1
    event_type: telegram_callback
    platform: event
  - event_data:
      command: /cam1
    event_type: telegram_command
    platform: event
  condition: []
  action:
  - data:
      entity_id: camera.esp32cam_one
      filename: /tmp/cam1.jpg
    service: camera.snapshot
  - delay: '5'
  - data:
      data:
        photo:
          caption: Camera 1
          url: /tmp/cam1.jpg
      message: Camera 1
    service: notify.telegram_td
- id: '1584977470639'
  alias: Telegram - Daily Beautiful News
  description: Every day send the daily Beautiful News image from https://informationisbeautiful.net/beautifulnews/
  trigger:
  - at: '14:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: sensor.beautifulnews
    service: homeassistant.update_entity
  - delay: '10'
  - data:
      data:
        photo:
          caption: '{{ state_attr(''sensor.beautifulnews'',''entries'')[0].title }}'
          url: '{{ (state_attr(''sensor.beautifulnews'',''entries'')[0].links | selectattr(''rel'',
            ''eq'',''enclosure'') | list)[0].href }}'
      message: test
    service: notify.telegram_td
- id: '1586469687141'
  alias: 'Globe: turn off after 30m'
  description: ''
  trigger:
  - entity_id: switch.sonoff_1000d4baef_1
    for: 00:30:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.sonoff_1000d4baef_1
    service: switch.turn_off
- id: '1588449990654'
  alias: 'Garage: Notification (repeat)'
  description: ''
  trigger:
  - minutes: /15
    platform: time_pattern
  condition: []
  action:
  - data_template:
      entity_id: media_player.living_room_display
      message: The garage door was opened {{ relative_time(states.binary_sensor.garage_door.last_changed)
        }} ago
    service: tts.google_translate_say
  - data_template:
      message: The garage door was opened {{ relative_time(states.binary_sensor.garage_door.last_changed)
        }} ago
      target:
      - '{{ states(''input_text.telegram_td'') }}'
      - '{{ states(''input_text.telegram_ad'') }}'
    service: telegram_bot.send_message
- id: '1588450174191'
  alias: 'Garage: Open'
  description: ''
  trigger:
  - device_id: 1278b53baee94a0092621cb7e29f04f5
    domain: binary_sensor
    entity_id: binary_sensor.garage_door
    platform: device
    type: opened
  condition: []
  action:
  - data_template:
      message: The garage door was opened
      target:
      - '{{ states(''input_text.telegram_td'') }}'
    service: telegram_bot.send_message
  - data: {}
    entity_id: automation.garage_notification_repeat
    service: automation.turn_on
  - data:
      entity_id: media_player.living_room_display
      message: The garage door was opened
    service: tts.google_translate_say
- id: '1588450370943'
  alias: 'Garage: Closed'
  description: ''
  trigger:
  - device_id: 1278b53baee94a0092621cb7e29f04f5
    domain: binary_sensor
    entity_id: binary_sensor.garage_door
    platform: device
    type: not_opened
  condition: []
  action:
  - data_template:
      message: The garage door was closed
      target:
      - '{{ states(''input_text.telegram_td'') }}'
    service: telegram_bot.send_message
  - data: {}
    entity_id: automation.garage_notification_repeat
    service: automation.turn_off
  - data:
        entity_id: media_player.living_room_display
        message: The garage door was closed
    service: tts.google_translate_say
