
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named ./themes
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
   base_url: https://tdroza.duckdns.org
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem
   
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

recorder:
  purge_keep_days: 2

pi_hole:
  - host: 192.168.1.215
  
media_player:
  - platform: kodi
    host: 192.168.1.238
    
speedtestdotnet:
  scan_interval:  
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload
    
telegram_bot:
  - platform: polling
    api_key: !secret telegram_ha_bot_key
    allowed_chat_ids: !secret telegram_bot_chat_ids
    
notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_bot_main_chat_id
   
google: 
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  
sonoff:
  username: !secret ewelink_username
  password: !secret ewelink_password
  
tuya: 
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: '44'
  platform: 'tuya'
  
binary_sensor:
  - platform: template
    sensors:
      show_commute_work:
        friendly_name: Display card between 07:00 and 09:00.
        entity_id: sensor.time
        value_template: >
           {{ 7 <= now().hour < 9 }}
  - platform: template
    sensors:
      show_commute_home:
        friendly_name: Display card between 16:00 and 18:00.
        entity_id: sensor.time
        value_template: >
           {{ 16 <= now().hour < 18 }}           
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: synologydsm
    host: 192.168.1.205
    username: hassio
    password: !secret synology
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - network_up
      - volume_percentage_used

  - platform: template
    sensors:
      hallway_motion_sensor_temperature_rounded:
        friendly_name: 'Hall Temp'
        value_template: '{{states.sensor.hallway_motion_sensor_temperature.state |round(0)}}'
  - platform: template
    sensors:
      white_temperature_2_rounded:
        friendly_name: 'Kitchen Temp'
        value_template: '{{states.sensor.white_temperature_2.state |round(0)}}'
  - platform: template
    sensors:
      bed1_temperature_rounded:
        friendly_name: 'Bed1 Temp'
        value_template: '{{states.sensor.bed1_temperature.state |round(0)}}'
  - platform: template
    sensors:
      seb_temperature_rounded:
        friendly_name: 'Seb Temp'
        value_template: '{{states.sensor.seb_temperature.state |round(0)}}'
  - platform: template
    sensors:
      reuben_temperature_rounded:
        friendly_name: 'Reuben Temp'
        value_template: '{{states.sensor.reu_temperature.state |round(0)}}'
  - platform: template
    sensors:
      bathroom_temperature_rounded:
        friendly_name: 'Bathroom Temp'
        value_template: '{{states.sensor.bathroom_temperature.state |round(0)}}'
  - platform: template
    sensors:
      ensuite_temperature_rounded:
        friendly_name: 'Ensuite Temp'
        value_template: '{{states.sensor.ensuite_temperature.state |round(0)}}'
  - platform: feedparser
    scan_interval: 43200
    name: QOTD
    feed_url: http://feeds.feedburner.com/theysaidso/qod/inspire
  - platform: feedparser
    name: BBC News
    feed_url: http://feeds.bbci.co.uk/news/rss.xml
    show_topn: 5
  - platform: google_travel_time
    name: 'Shipley to Leeds'
    api_key: !secret gcloud_api_key
    origin: Shipley, UK
    destination: Leeds, UK
    scan_interval: 3600
    options:
      mode: transit
      transit_mode: train
#  - platform: google_travel_time
#    name: 'Shipley to Bradford'
#    api_key: !secret gcloud_api_key
#    origin: Shipley, UK
#    destination: Bradford, UK
#    scan_interval: 3600
#    options:
#      mode: transit
#      transit_mode: train      
  - platform: uk_transport
    scan_interval: 86400
    app_id: !secret uk_transport-app_id
    app_key: !secret uk_transport-app_key
    queries:
      - mode: train
        origin: SHY
        destination: LDS    
  - platform: uk_transport
    scan_interval: 86400
    app_id: !secret uk_transport-app_id
    app_key: !secret uk_transport-app_key
    queries:
      - mode: train
        origin: LDS
        destination: SHY   
  - platform: rest
    resource: https://complimentr.com/api
    method: GET
    name: compliment
    scan_interval: 3600
    value_template: '{{ value_json.compliment }}'

homeassistant:
  customize: !include customize.yaml
  name: Home
  unit_system: metric

zone: !include zones.yaml
    
ifttt:
  key:
    tom: !secret tom_ifttt
    anna: !secret anna_ifttt

device_tracker:
  - platform: bt_smarthub
    host: 192.168.1.254
    interval_seconds: 30
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
  - platform: google_maps
    username: tom.annalou@gmail.com
    