# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named ./themes
  extra_module_url:
    - /local/GlobalVariables.js
  
# Text to speech
tts:
  - platform: google_translate
    service_name: google_translate_say

automation: !include automations.yaml
automation old: !include_dir_merge_list automations
binary_sensor: !include includes/binary_sensors.yaml
device_tracker: !include includes/device_trackers.yaml
group: !include groups.yaml
http: !include includes/http.yaml
light: !include includes/light_groups.yaml
notify: !include includes/notify.yaml
recorder: !include includes/recorder.yaml
script: !include scripts.yaml
sensor: !include includes/sensors.yaml
zone: !include zones.yaml
downloader: !include includes/downloader.yaml
neato: !include includes/neato.yaml
plant: !include includes/plant.yaml

pi_hole:
  - host: 192.168.1.215

octoprint:
  host: octopi.lan
  api_key: '97D2B94F6BE14938871A03CE0E1D23C0'
  name: 'Printer'
  bed: true
  number_of_tools: 1

speedtestdotnet:
  scan_interval:  
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload

telegram_bot:
  - platform: polling
    api_key: !secret telegram_ha_bot_key
    allowed_chat_ids: 
      - !secret telegram_bot_chat_id_td
      - !secret telegram_bot_chat_id_ad

input_text:
  telegram_td: 
    initial: !secret telegram_bot_chat_id_td
  telegram_ad: 
    initial: !secret telegram_bot_chat_id_ad
google: 
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  
sonoff:
  username: !secret ewelink_username
  password: !secret ewelink_password
  grace_period: 600
  
tuya: 
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: '44'
  platform: 'tuya'

homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp
    - /config/www/cams

ifttt:
  key:
    tom: !secret tom_ifttt
    anna: !secret anna_ifttt

google_assistant: !include includes/google_assistant.yaml

zoom: 
    client_id: !secret zoom_client_id
    client_secret: !secret zoom_client_secret
    verification_token: !secret zoom_verification_token
    
