# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  
frontend:
  themes: !include_dir_merge_named ./themes
  extra_module_url:
    - /local/GlobalVariables.js
  
# Text to speech
tts:
  - platform: google_translate
    service_name: google_translate_say

automation: !include automations.yaml
automation old: !include_dir_merge_list automations
binary_sensor: !include includes/binary_sensors.yaml
camera: !include includes/camera.yaml
cover: !include includes/covers.yaml
device_tracker: !include includes/device_trackers.yaml
downloader: !include includes/downloader.yaml
energy:
google_assistant: !include includes/google_assistant.yaml
group: !include includes/groups.yaml
http: !include includes/http.yaml
light: !include includes/light_groups.yaml
notify: !include includes/notify.yaml
plant: !include includes/plant.yaml
recorder: !include includes/recorder.yaml
rest: !include includes/restful.yaml
rest_command: !include includes/rest.yaml
script: !include scripts.yaml
shell_command: !include includes/shell.yaml
sensor: !include includes/sensors.yaml
template: !include includes/template.yaml
utility_meter: !include includes/utility.yaml
zone: !include includes/zones.yaml

sonoff:
  username: !secret ewelink_username
  password: !secret ewelink_password
  sensors: power, current, voltage
  force_update: power

input_text:
  telegram_td: 
    initial: !secret telegram_bot_chat_id_td
  telegram_ad: 
    initial: !secret telegram_bot_chat_id_ad

homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp
    - /config/www/cams
    - /config/quotes_clock

ifttt:
  key:
    tom: !secret tom_ifttt
    anna: !secret anna_ifttt
