# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named ./themes
  extra_module_url:
    - /local/GlobalVariables.js
  
# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
automation old: !include_dir_merge_list automations
binary_sensor: !include includes/binary_sensors.yaml
device_tracker: !include includes/device_trackers.yaml
group: !include groups.yaml
http: !include includes/http.yaml
light: !include includes/light_groups.yaml
notify: !include includes/notify.yaml
recorder: !include includes/recorder.yaml
script: !include scripts.yaml
sensor: !include includes/sensors.yaml
zone: !include zones.yaml
downloader: !include includes/downloader.yaml

pi_hole:
  - host: 192.168.1.215

octoprint:
  host: octopi.lan
  api_key: '97D2B94F6BE14938871A03CE0E1D23C0'
  name: 'Printer'
  bed: true
  number_of_tools: 1

media_player:
  - platform: kodi
    host: 192.168.1.170

speedtestdotnet:
  scan_interval:  
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload

telegram_bot:
  - platform: polling
    api_key: !secret telegram_ha_bot_key
    allowed_chat_ids: 
      - !secret telegram_bot_chat_id_td
      - !secret telegram_bot_chat_id_ad

input_text:
  telegram_td: 
    initial: !secret telegram_bot_chat_id_td
  telegram_ad: 
    initial: !secret telegram_bot_chat_id_ad
google: 
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  
sonoff:
  username: !secret ewelink_username
  password: !secret ewelink_password
  grace_period: 600
  
tuya: 
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: '44'
  platform: 'tuya'

homeassistant:
  customize: !include customize.yaml
  name: Home
  unit_system: metric
  whitelist_external_dirs:
    - /tmp
    - /config/www/cams

android_ip_webcam:
  - host: 192.168.1.175
    port: 8080
    username: tdroza
    password: !secret ipcam_password
    sensors:
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - sound
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - motion_detect
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording

camera:
  - platform: local_file
    file_path: /config/www/cams/cam1.jpg
    name: esp32cam_lastimage
ifttt:
  key:
    tom: !secret tom_ifttt
    anna: !secret anna_ifttt

google_assistant: !include includes/google_assistant.yaml
