# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named ./themes
  extra_module_url:
    - /local/GlobalVariables.js
  
# Text to speech
tts:
  - platform: google_translate
    service_name: google_translate_say

automation: !include automations.yaml
automation old: !include_dir_merge_list automations
binary_sensor: !include includes/binary_sensors.yaml
device_tracker: !include includes/device_trackers.yaml
downloader: !include includes/downloader.yaml
google_assistant: !include includes/google_assistant.yaml
group: !include groups.yaml
http: !include includes/http.yaml
light: !include includes/light_groups.yaml
neato: !include includes/neato.yaml
nest: !include includes/nest.yaml
notify: !include includes/notify.yaml
plant: !include includes/plant.yaml
recorder: !include includes/recorder.yaml
rest_command: !include includes/rest.yaml
script: !include scripts.yaml
sensor: !include includes/sensors.yaml
utility_meter: !include includes/utility.yaml
zone: !include zones.yaml

sonoff:
  username: !secret ewelink_username
  password: !secret ewelink_password
  sensors: power, current, voltage
  force_update: power

telegram_bot:
  - platform: polling
    api_key: !secret telegram_ha_bot_key
    allowed_chat_ids: 
      - !secret telegram_bot_chat_id_td
      - !secret telegram_bot_chat_id_ad

input_text:
  telegram_td: 
    initial: !secret telegram_bot_chat_id_td
  telegram_ad: 
    initial: !secret telegram_bot_chat_id_ad
google: 
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp
    - /config/www/cams

ifttt:
  key:
    tom: !secret tom_ifttt
    anna: !secret anna_ifttt
