- platform: template
  sensors:
    tom_in_meeting:
      friendly_name: "Is Tom in a Zoom/Teams meeting?"
      value_template: >-
        "{{ is_state('binary_sensor.zoom_tombjss',"on") or is_state('sensor.teams_activity','In a call') }}"
      icon_template: >
        {% if is_state("binary_sensor.tom_in_meeting", "on") %}
          mdi:phone-in-talk
        {% else %}
          mdi:phone-hangup
        {% endif %}
    washer:
      friendly_name: "Washing machine"
      value_template: >-
        {{ state_attr('switch.sonoff_10003a0e20', 'power')|float > 10 }}
      icon_template: >
        {% if is_state("binary_sensor.washer", "on") %}
          mdi:washing-machine
        {% else %}
          mdi:washing-machine-off
        {% endif %}
      delay_on: 
        minutes: 5
      delay_off:
        seconds: 90            
    show_commute_work:
      friendly_name: Display card between 07:00 and 09:00.
      value_template: >
         {{ 7 <= now().hour < 9 }}
    show_commute_home:
      friendly_name: Display card between 16:00 and 18:00.
      value_template: >
         {{ 16 <= now().hour < 18 }}
- platform: workday
  country: GB
  province: England
- platform: workday
  name: workday_anna
  excludes: [sat, sun, mon, wed, holiday]
  country: GB
  province: England

