- platform: template
  sensors:
    washer:
      friendly_name: "Washing machine"
      value_template: >-
        {{ states('sensor.sonoff_10003a0e20_power')|float > 10 }}
      icon_template: >
        {% if is_state("binary_sensor.washer", "on") %}
          mdi:washing-machine
        {% else %}
          mdi:washing-machine-off
        {% endif %}
      delay_on: 
        minutes: 2
      delay_off:
        seconds: 90            
    dishwasher:
      friendly_name: "Dishwasher"
      value_template: >-
        {{ states('sensor.sonoff_dishwasher_power')|float > 10 }}
      icon_template: >
        {% if is_state("binary_sensor.dishwasher", "on") %}
          mdi:dishwasher
        {% else %}
          mdi:dishwasher-off
        {% endif %}
      delay_on: 
        minutes: 1
      delay_off:
        seconds: 30    
    show_commute_work:
      friendly_name: Display card between 07:00 and 09:00.
      value_template: >
         {{ 7 <= now().hour < 9 }}
    show_commute_home:
      friendly_name: Display card between 16:00 and 18:00.
      value_template: >
         {{ 16 <= now().hour < 18 }}