- platform: bt_smarthub
  host: 192.168.1.254
  interval_seconds: 15
  consider_home: 300
  new_device_defaults:
    track_new_devices: false
- platform: google_maps
  username: tom.annalou@gmail.com
