- platform: group
  name: Living Room Lights
  entities:
  - light.living_room_1
  - light.living_room_2
- platform: group
  name: Main Bedroom Lights
  entities:
  - light.main_bedroom_ceiling
  - light.main_bedroom_bloom
- platform: group
  name: Reubens Bedroom Lights
  entities:
  - light.rname
  - light.reuben_ceiling
- platform: group
  name: Sebs Bedroom Lights
  entities:
  - light.seb_s_colour
  - light.sebs_lamp
- platform: group
  name: Second Bedroom Lights
  entities:
    - light.second_bedroom
    - light.desk
    - light.anna_s_desk
