
- platform: group
  name: Upstairs Light Group
  entities:
    - light.main_bedroom_ceiling
    - light.main_bedroom_bloom
    - light.second_bedroom_ceiling
    - light.toms_desk_master
    - light.annas_desk
    - light.sebs_ceiling
    - light.sebs_lamp
    - light.rname
    - light.reubens_ceiling
    