esphome:
  name: d1_mini_distance_temp
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password
  domain: ".lan"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1 Mini Distance Temp"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dallas:
  - pin: D5
    update_interval: 300s
  
sensor:
  - platform: dallas
    address: 0xB701187D0433FF28
    name: "Sourdough Temperature"

  - platform: ultrasonic
    update_interval: 60s
    trigger_pin: D1
    echo_pin: D2
    filters:
    - lambda: |-
        if (x <= 0.107) {
          return 10.7 - (100 * x);
        } else return {};
  
    - sliding_window_moving_average:
        window_size: 5
        send_every: 5
    unit_of_measurement: "cm"
    name: "Sourdough Height"