esphome:
  name: d1mini_motion_seb
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password
  domain: ".lan"


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1Mini Temp Pir Hotspot"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dallas:
  - pin: D3
    update_interval: 300s
  
sensor:
  - platform: dallas
    address: 0x760119500218FF28
    name: "Seb D1 Temperature"


binary_sensor:
  - platform: gpio
    pin: D1
    name: "Seb D1 Motion"
    device_class: motion
