esphome:
  name: "${device_name}"
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password
  domain: ".lan"


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: !secret wifi_password

substitutions:
  device_name: "d1mini_motion_seb"
  friendly_name: "Seb D1"
  
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dallas:
  - pin: D3
    update_interval: 300s
  
sensor:
  - platform: dallas
    address: 0x760119500218FF28
    name: "${friendly_name} Temperature"

binary_sensor:
  - platform: gpio
    pin: D1
    name: "${friendly_name} Motion"
    device_class: motion
  - platform: status
    name: "${friendly_name}  Status"
