esphome:
  name: d1mini-knock
  platform: ESP8266
  board: d1_mini

substitutions:
  device_name: "d1mini_knock"
  friendly_name: "D1 Mini Knock"
  
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password
  domain: ".lan"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} AP"
    password: !secret wifi_password
    
captive_portal:

i2c:
  sda: D2
  scl: D1
  
sensor:
  - platform: bmp280
    address: 0x76
    temperature:
      name: "Office Temperature"
      oversampling: 16x
    pressure:
      name: "Office Pressure"
    update_interval: 60s
    
binary_sensor:
  - platform: gpio
    pin: D3
    name: "${friendly_name}"
    device_class: vibration
    on_double_click:
      min_length: 15ms
      max_length: 100ms
      then:
        - homeassistant.event:
            event: esphome.knock_double_click
            data:
              title: Double-click Vibration!  
  - platform: status
    name: "${friendly_name}  Status"