esphome:
  name: "${device_name}"
esp8266:
    board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".lan"
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: !secret wifi_password

substitutions:
  device_name: "d1mini-motion-reuben"
  friendly_name: "Reu D1"
  
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

one_wire:
  - pin: D3
    platform: gpio
  
sensor:
  - platform: dallas_temp
    update_interval: 600s
    address: 0x9401187D0BC7FF28
    name: "${friendly_name} Temperature"
    filters:
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 23.0 -> 17.8
          - 23.2 -> 17.9
          - 23.6 -> 18.5
          - 24.0 -> 18.6
          - 24.1 -> 18.9
          - 24.2 -> 19.1
          - 24.8 -> 19.4
          
binary_sensor:
  - platform: gpio
    pin: D1
    name: "${friendly_name} Motion"
    device_class: motion
  - platform: status
    name: "${friendly_name} Status"

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic