esphome:
  name: ${device_name}
  platform: ESP32
  board: esp-wrover-kit
  on_boot:
    - switch.template.publish:
        id: esp32_status
        state: ON
  on_shutdown:
    - switch.template.publish:
        id: esp32_status
        state: OFF
      
substitutions:
  device_name: esp32cam_one
  friendly_name: ESP32Cam-One
wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password
  domain: ".lan"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Cam One Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

output:
  - platform: ledc
    channel: 2
    id: flash_led
    pin: GPIO4

light:
  - platform: monochromatic
    name: "esp32cam_one flash"
    output: flash_led

deep_sleep:
  run_duration: 1min
  sleep_duration: 5min
    
switch:
  - platform: template
    name: "ESP32Cam Status"
    id: esp32_status
    optimistic: true

text_sensor:
- platform: version
  hide_timestamp: true
  name: "${friendly_name} ESPHome Version"
  entity_category: diagnostic
- platform: wifi_info
  ip_address:
    name: "${friendly_name} IP Address"
    icon: mdi:wifi
    entity_category: diagnostic
  ssid:
    name: "${friendly_name} Connected SSID"
    icon: mdi:wifi-strength-2
    entity_category: diagnostic
    
esp32_camera:
  name: esp32cam_one
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1024x768
  jpeg_quality: 20
  max_framerate: 1 fps

