substitutions:
  name: "esp32-bt-proxy-upstairs"
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false


wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password
