substitutions:
  device_name: "esp32_ble_relay"
  friendly_name: "ESP32 BLE Relay"
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password
  domain: ".lan"
  
logger:

api: 

ota: 

# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:35:F1:F7
    temperature:
      name: "Kitchen Temperature"
    humidity:
      name: "Kitchen Humidity"
    battery_level:
      name: "Kitchen Battery"
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:35:ED:5E
    temperature:
      name: "Office Temperature"
    humidity:
      name: "Office Humidity"
    battery_level:
      name: "Office Battery"
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:36:B3:94
    temperature:
      name: "Bathroom temperature"
    humidity:
      name: "Bathroom Humidity"
    battery_level:
      name: "Bathroom Battery"
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:36:B8:3D
    temperature:
      name: "Ensuite Temperature"
    humidity:
      name: "Ensuite Humidity"
    battery_level:
      name: "Ensuite Battery"
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:66:1D:E5
    temperature:
      name: "Basil Temperature"
    moisture:
      name: "Basil Moisture"
    illuminance:
      name: "Basil Illuminance"
    conductivity:
      name: "Basil Soil Conductivity"
    battery_level:
      name: "Basil Battery Level"
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:66:20:EA
    temperature:
      name: "Rose Temperature"
    moisture:
      name: "Rose Moisture"
    illuminance:
      name: "Rose Illuminance"
    conductivity:
      name: "Rose Soil Conductivity"
    battery_level:
      name: "Rose Battery Level"

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic