esphome:
  name: sensor_soil
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "Byron"
  password: !secret byron_wifi
  domain: ".home"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: adc
    unit_of_measurement: "%"
    icon: "mdi:flower-outline"
    accuracy_decimals: 0
    pin: A0
    name: "Soil Moisture Level"
    filters:
    - calibrate_linear:
        - 0.34 -> 100
        - 0.98 -> 0
    update_interval: 5s
deep_sleep:
  run_duration: 60s
  sleep_duration: 10min