esphome:
  name: sensor_d1mini_dht22_green
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password
  domain: ".lan"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: D1
    model: DHT22
    update_interval: 300s
    temperature:
      name: "Living Room Temp"
    humidity:
      name: "Living Room Humidity"
  - platform: adc
    pin: VCC
    name: "Living Room Voltage"
    update_interval: 600s