esphome:
  name: sensor_esp01_dht22_motion_white
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password
  domain: ".lan"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: GPIO2
    model: DHT22
    update_interval: 300s
    temperature:
      name: "Dining Room Temperature"
    humidity:
      name: "Dining Room Humidity"
  - platform: adc
    pin: VCC
    name: "White Voltage"
    update_interval: 300s
