esphome:
  name: sensor_esp01_dht22_motion_white
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".home"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: GPIO2
    model: DHT22
    update_interval: 300s
    temperature:
      name: "White Temperature"
    humidity:
      name: "White Humidity"
  - platform: adc
    pin: VCC
    name: "White Voltage"
    update_interval: 300s

#binary_sensor:
#  - platform: gpio
#    pin: GPIO0
#    name: "Kitchen Motion Sensor"
#    device_class: motion