esphome:
  name: "${device_name}"
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password
  domain: ".lan"
  ap: 
    ssid: "${device_name}"
    
substitutions:
  device_name: "sensor-d1mini-dht22-bed1"
  friendly_name: "Bed1"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: D1
    model: DHT22
    update_interval: 300s
    temperature:
      name: "${friendly_name} Temperature"
    humidity:
      name: "${friendly_name} Humidity"
  - platform: adc
    pin: VCC
    name: "Bed1 Voltage"
    update_interval: 600s

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic
         
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"