wifi:
  networks:
    - ssid: !secret wifi_iot_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  domain: ".lan"
  manual_ip:
    static_ip: 192.168.1.82
    gateway: 192.168.1.254
    subnet: 255.255.255.0
  
  ap:
    ssid: ${devicename}

# Enable the captive portal for inital WiFi setup
captive_portal:

substitutions:
  devicename: tagreader
  friendly_name: TagReader

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini
  includes:
  - ndef.h
  libraries:
  - https://github.com/jesserockz/NDEF.git
  - https://github.com/jesserockz/PN532.git#esphome-i2c

# notify on api connection success
  on_boot:
    priority: -10
    then:
    - wait_until:
        api.connected:
    - logger.log: API is connected!
   
# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable OTA upgrade
ota:

# Enable SPI interface
i2c:
  
text_sensor:
- platform: custom
  lambda: |-
    auto ndef_tag_reader = new NDEFTagReader();
    App.register_component(ndef_tag_reader);
    return {ndef_tag_reader};
  text_sensors:
    name: "${friendly_name} Tag"
    id: scanned_tag
    on_value:
      then:
      - if:
          condition:
            lambda: return x != "";
          then:
          - homeassistant.tag_scanned: !lambda 'return x;'
         